//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Net.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public long Id { get; set; }

        public System.DateTime KayitTarihi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Gorevi { get; set; }
        public int Maas { get; set; }
    }
}
