//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Net.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler
    {
        public string Meslek { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> KontenjanSayisi { get; set; }
        public long id { get; set; }
    }
}
